source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Nerde Yesem' do
 
 pod 'Alamofire', '~> 5.0.0-beta.5'
 pod 'Kingfisher', '~> 4.0'
 pod 'NVActivityIndicatorView'
 pod 'GoogleMaps'
 pod 'GooglePlaces'
end
